#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=key --value="$key"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.env.example" --destination="$install_dir/config.env"

chmod 600 "$install_dir/config.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Manage and promote voluntary work in associations" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL THE APP
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
    python3 -m venv $install_dir/venv
    ynh_hide_warnings $install_dir/venv/bin/pip install benevalibre==$(ynh_app_upstream_version)
    ynh_exec_as $app python -m benevalibre migrate
    ynh_exec_as $app python -m benevalibre collectstatic
    ynh_exec_as $app python -m benevalibre createsuperuser
popd

chown -R $app:www-data "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
