#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# ynh_setup_source --dest_dir="$install_dir" --keep="config.env"
ynh_safe_rm "$install_dir/venv"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="config.env.example" --destination="$install_dir/config.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Manage and promote voluntary work in associations" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL THE APP
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
    python3 -m venv $install_dir/venv
    ynh_hide_warnings $install_dir/venv/bin/pip install benevalibre==$(ynh_app_upstream_version) gunicorn
    ynh_hide_warnings $install_dir/venv/bin/pip install psycopg2-binary
    ynh_exec_as_app $install_dir/venv/bin/python3 -m benevalibre migrate
    ynh_exec_as_app $install_dir/venv/bin/python3 -m benevalibre collectstatic
    # ynh_hide_warnings make update
popd

chown -R $app:www-data "$install_dir"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
